version: "3.8"
services:

  web:
    container_name: httpd
    build: .
    ports:
      - 80:80
    volumes:
      - ../src:/var/www
  #   depends_on:
  #     - mysql

  # mysql:
  #   container_name: mysqld
  #   build: ./mysql
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - ./mysql/data:/var/lib/mysql
  #   command: /usr/sbin/mysqld