# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.9"
  config.vm.network "private_network", ip: "192.168.56.10"
  
  # Apache config files
  config.vm.synced_folder "./apache/sites.d", "/etc/httpd/sites.d", owner: "root", group: "root"

  config.vm.synced_folder "./apache/ssl.d", "/etc/httpd/ssl.d", owner: "root", group: "root"

  # Application files
  config.vm.synced_folder "../../repo", "/var/www", owner: "vagrant", group: "vagrant"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.name = "CentOS-7.9-PHP-8"
  end
end
